version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net
  server:
    build:
      context: ./dockerfiles/server
      dockerfile: Dockerfile
    container_name: server
    networks:
      - rabbitmq_go_net
    depends_on:
      rabbitmq:
        condition: service_healthy
  client:
    build:
      context: ./dockerfiles/client
      dockerfile: Dockerfile
    container_name: client
    networks:
      - rabbitmq_go_net
    depends_on:
      rabbitmq:
        condition: service_healthy
      server:
        condition: service_healthy
networks:
  rabbitmq_go_net:
    driver: bridge
